#!/bin/sh
PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH

case $1 in
	start|stop)
		swapoff -a >/dev/null 2>&1 || :
		umount -a -r >/dev/null 2>&1 || :
		case $0 in
			*rc6.d*) reboot -f ;;
			*) halt -f ;;
		esac
		;;
	*)
		printf '%s\n' "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
