#!/bin/sh
PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH

case $1 in
	start)
		mount -a -t nonfs,nonfs4,nosmbfs,nocifs 2>/dev/null || :
		swapon -a 2>/dev/null || :
		;;
	stop)
		swapoff -a >/dev/null 2>&1 || :
		umount -a -r -t nosysfs,noproc,nodevtmpfs >/dev/null 2>&1 || :
		;;
	*)
		printf '%s\n' "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
