#!/bin/sh
exec 2>&1
if command -v dropbearkey >/dev/null 2>&1; then
  mkdir -p /etc/dropbear
  [ -f /etc/dropbear/dropbear_rsa_host_key ] || dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key >/dev/null
fi
exec /usr/sbin/dropbear -F -E
