#!/bin/sh
PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH
sv force-shutdown /etc/runit/runsvdir/default/* >/dev/null 2>&1 || :
udevadm control --exit >/dev/null 2>&1 || :
swapoff -a >/dev/null 2>&1 || :
umount -a -r >/dev/null 2>&1 || :
