#!/bin/sh
exec 2>&1
if command -v exportfs >/dev/null 2>&1; then exportfs -ra || :; fi
if command -v rpc.statd >/dev/null 2>&1; then rpc.statd --no-notify || :; fi
if command -v rpc.nfsd >/dev/null 2>&1; then rpc.nfsd 8 || :; fi
exec /usr/sbin/rpc.mountd -F
