#!/bin/sh
### BEGIN INIT INFO
# Provides:          nftables
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     S
# Default-Stop:      
# Short-Description: nftables packet filter
### END INIT INFO

if [ -f /etc/rc.d/init.d/functions ]; then
	. /etc/rc.d/init.d/functions
elif [ -f /etc/init.d/functions ]; then
	. /etc/init.d/functions
fi

NAME=nftables
DAEMON="/usr/sbin/nft"
DAEMON_ARGS="-f /etc/nftables.conf"
PIDFILE="/run/nftables.pid"
USER=""

start() {
	eval "$DAEMON" $DAEMON_ARGS
	return $?
}

stop() {
	return 0
}

status() {
	pidofproc -p "$PIDFILE" "$DAEMON"
}

case $1 in
	start) start ;;
	stop) stop ;;
	restart) stop; start ;;
	status) status ;;
	*) printf '%s\n' "Usage: $0 {start|stop|restart|status}" >&2; exit 1 ;;
esac
